<?php
$this->headTitle('Welcome');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home')
            ]);
?>

<h1>Login to Continue</h1>

<p>
    Click the <em>Login</em> button at the top right. To sign in, use the 
    following credentials...
    <ul>
        <li>Username: <em>admin@example.com</em></li>
        <li>Password: <em>Secur1ty</em></li>
    </ul>    
</p>



